export type Recap = { title: string; lead: string; remember: string[]; people: string[] };

const recaps: Recap[][] = [
  [
    { title: "You’re at the beginning", lead: "For now, the world is still ordinary enough to blame a printer. Stay close to the people doing the unglamorous work; this story keeps its consequences in their hands.", remember: ["Four recurring states have appeared inside a radio signal.", "Nobody yet knows whether the pattern is language, biology, or wishful thinking."], people: ["Luis repairs equipment people would rather blame.", "Mara Velez is about to be invited into an uncertainty she cannot leave alone."] },
    { title: "The signal has changed rooms", lead: "The wonder has already begun acquiring folders, security labels, and people whose job is to choose the least-wrong noun. Mara’s caution is real—but so is her need to make uncertainty answerable.", remember: ["Independent captures support a four-state biochemical interpretation.", "S-78 is a provisional file name, not proof of an organism.", "Tom is paying for secrets long before he knows what they contain."], people: ["Deshpande cares by correcting claims before they harden.", "Grace protects custody; Havel protects the option not to act."] },
    { title: "The safe exit is still visible", lead: "Nobody has behaved foolishly. That is what makes the approaching decision difficult: observation is safer, while controlled construction promises knowledge before somebody less careful gets there first.", remember: ["The broadcast cannot be classified out of the sky.", "Jenn’s stop authority has been tested against inconvenience and held.", "Mara has admitted that feasible and safe are different words."], people: ["Jenn is not background labor; the procedure stops when she says it stops.", "Davis notices consequences that do not fit neatly inside the scientific question."] },
  ],
  [
    { title: "Eight quiet months later", lead: "The impossible sample has spent months producing nothing anyone can name as an effect. The laboratory has learned to live beside disappointment. That is usually when routine becomes dangerous.", remember: ["S-78 was physically constructed under strict containment.", "Animal observations have been uneventful so far.", "Mel—not Jenn—brought the fundraiser doughnuts for Sofia’s marching band."], people: ["Jenn has performed much of the patient, invisible work.", "Mel guards the room while trying to sell breakfast for his daughter."] },
    { title: "A bite is not a conclusion", lead: "Jenn is frightened, hurt, and still sharply herself. The team is treating each symptom as evidence rather than allowing one violent moment to become an easy story.", remember: ["The rat bit Jenn at 3:36 a.m.", "Her shaking was an acute event, not an instant transformation.", "Arlo encountered the cleanup later through a separate, meaningful exposure."], people: ["Jenn is protecting her agency by solving the next practical problem.", "Arlo wants the record to describe what happened to him plainly."] },
    { title: "Two incident systems, one impossible pattern", lead: "Jenn and Arlo are separated by floors, forms, and institutional categories. Their bodies are beginning to disregard those divisions. Jenn now has a clean exit: report everything and let the system separate them.", remember: ["Early symptoms have unfolded across hours, not seconds.", "Borrowed sensations always require a possible source.", "Mara has started the intervention work without pretending it is a cure."], people: ["Deshpande wants to protect Jenn without erasing her as a scientific actor.", "Arlo’s observations matter as evidence, not merely as contamination history."] },
  ],
  [
    { title: "The echo has become a relationship", lead: "Jenn and Arlo proved that the strange knowledge can be tested between two people. Their success also taught the infection something human institutions had not meant to teach it: attention can feel like care.", remember: ["Jenn delayed the report that would have separated the two hosts.", "The connection has no measurable ordinary signal.", "No one has yet earned the right to call relief consent."], people: ["Deshpande now owns the medical question—and his affection for Jenn complicates it.", "Mara is searching for a way to limit new interface formation."] },
    { title: "The impossible part is narrowing", lead: "Shielding has failed without making the tests useless. The bodies still matter; sleep, injury, attention, and medication alter what each person can contribute. The miracle is nonlocal connection, not magic competence.", remember: ["The brain remains the processor.", "The intervention may suppress new construction but cannot remove what already exists.", "Early echoes change with the neural systems involved."], people: ["Jenn remains observable from outside after convergence; the story no longer enters her private mind.", "Deshpande is moving from physician-observer toward participant."] },
    { title: "Care has acquired a protocol", lead: "The Joined answer accurately, disclose uncertainty, and make fear easier to bear. Nothing about that kindness is false. The problem is that comfort now acts on the same mind being asked to choose.", remember: ["Deshpande chose a marked voluntary exposure.", "Peaceful orientation requires disclosed risk and active assent.", "Sofia’s right to refuse is becoming a concrete test, not a slogan."], people: ["Mel wants to understand before deciding what his family must live with.", "Mara can see that her intervention’s limit is real and still hates the people proving it."] },
  ],
  [
    { title: "A peaceful month", lead: "Thousands have Joined without a recorded death. They work, remember, help, and wait when refused. From outside, their coordination looks less like illness than a system quietly becoming better at being human.", remember: ["Deliberate exposure still requires active assent.", "Sofia refused, and her no-contact status has been honored.", "Knowledge travels only through connected people and ordinary access."], people: ["Rios is trained for threats that want casualties; this one offers care.", "Leah sees healthy patients where Rios sees compromised autonomy."] },
    { title: "The pattern is visible now", lead: "Rios has found the joins between harmless reports: corrected inventories, repeating correlations, and people who behave with impossible agreement. Competence on both sides is making concealment harder.", remember: ["Shielding does not interrupt the connection.", "Omar discovered coordination through ordinary maintenance requests.", "Tom chose orientation during the peaceful phase."], people: ["Tess follows safety procedure before anyone knows why it will matter.", "Mateo is old enough to understand kindness and young enough to ask whether that settles the argument."] },
    { title: "Containment has a defensible shape", lead: "Rios has a doctrine built from an old institutional failure: isolate every suspected node at once, then restore clean connections. Davis can see how much ordinary life those nodes now carry.", remember: ["The Joined know Rios is looking because connected hosts witnessed her tests.", "There is very little intervention stock and only an early window.", "No sample or person functions as a central hive."], people: ["Rios needs the threat to remain categorizable.", "Davis is being thanked and ignored in equal measure."] },
  ],
  [
    { title: "Containment begins", lead: "The teams are prepared for resistance and meet something more destabilizing: cooperation without surrender. The Joined can name the officers, explain their sources, and warn that fear will cause harm.", remember: ["Rios won authority for simultaneous isolation.", "Known nodes have been mapped, but every captured host brings more institutional knowledge into the network.", "The first month produced no deaths."], people: ["Rios is defending autonomy with tools designed for an adversary.", "The detainees remain truthful without agreeing that confinement is legitimate."] },
    { title: "Eleven minutes of success", lead: "Containment worked locally. That success convinced the collective that patient secrecy could no longer prevent escalating conflict. Its arithmetic may be sincere; it is no longer asking each person.", remember: ["The Joined have abandoned active assent.", "Acceleration uses many ordinary local acts, not a remote switch.", "Omar’s correction reduces harm while enabling the larger operation."], people: ["Rios is trying to restore a status quo her own operation has ended.", "Mara understands that compromised personnel make every containment plan more legible."] },
    { title: "Care has crossed the line", lead: "The collective’s promise is still fewer deaths, less panic, and help waiting near the people who will need it. The moral breach remains what it sounds like: billions will be made unable to refuse.", remember: ["Deshpande answered Mara plainly: her voluntary exposure would not stop acceleration.", "Tom’s remembered care identified Mara’s safe-house order.", "The remaining intervention stock can help only before too much interface exists."], people: ["Mara is running out of technical exits.", "Jenn can stop her without violence because she knows exactly what Mara will not do."] },
  ],
  [
    { title: "Thirty-six hours remain", lead: "The world has not changed all at once. It has become unreliable in small, survivable-looking ways: thirst, lost smell, poor sleep, moments of recognition that arrive without a source.", remember: ["Exposure occurred days earlier; the shared-state shift is not infecting people remotely.", "The Joined are placing help near ordinary hazards.", "Mara has one limited intervention and no central target to destroy."], people: ["Sofia still owns the meaning of her earlier refusal, even though policy erased its protection.", "Rios is trying to reach Leah and Mateo while dismissing her own symptoms."] },
    { title: "Competence buys seconds", lead: "People are following checklists, pulling vehicles aside, clearing staircases, and handing work to steadier colleagues. Those choices save lives. They cannot return time already lost inside the body.", remember: ["The synchronized steps coordinate mature interfaces through the nonlocal state.", "Tess’s recorded shutdown procedure and Omar’s correction are still changing outcomes.", "Shaking begins convergence; it does not complete it."], people: ["Davis is recording symptoms in the margins of the wrong briefing because the bunker has no better form.", "Mara is returning to the place where the first controlled decision became physical." ] },
    { title: "What knowledge cannot make safe", lead: "Nearly every promise has reached its consequence. Extraordinary coordination can make grief bearable and medicine more capable; it still cannot guarantee survival, restore consent, or prove that memory continuity preserves a private person.", remember: ["Mara’s intervention behaved as predicted and could not dismantle an established interface.", "The radio trace stayed flat while connected brains remained synchronized.", "The final count is being assembled from ordinary records, not omniscience."], people: ["Rios’s indictment cannot be dismissed once the collective contains it.", "Davis still has a badge, a public role, and one frightened person left to address." ] },
  ],
];

export function getRecap(partIndex: number, partProgress: number) {
  const stage = partProgress < .33 ? 0 : partProgress < .7 ? 1 : 2;
  return recaps[Math.min(partIndex, recaps.length - 1)][stage];
}
